version: "3.1"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - STATS_USER=admin
      - STATS_PASS=admin

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
  ui:
    image: dockervoyagerlabs/dfproxy:1.7.4
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.servicePath=/ui
        - com.df.reqPathSearch=/ui
        - com.df.port=3333
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PROXY_HOST_AND_PORT=http://proxy:8080

networks:
  proxy:
    external: true
